# docker-compose.yaml
services:
  # nginx
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
        - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        - ./app:/var/www/html

  # php
  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - /var/www/html/vendor
      - ./app:/var/ww/html
  # mysql
  db:
    image: mysql:9.0
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: docker-php
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
  # redis

volumes:
  mysqldata:

